version: "3"
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "shop-orders-events:1:1,kitchen-orders-events:1:1"
    depends_on:
      - zookeeper
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: kitchen-test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "6432:5432"
