// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: kitchen_api.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KitchenOrderStatus int32

const (
	KitchenOrderStatus_KitchenOrderStatusInvalid KitchenOrderStatus = 0
	KitchenOrderStatus_kitchenOrderStatusNew     KitchenOrderStatus = 1
	KitchenOrderStatus_kitchenOrderStatusCooking KitchenOrderStatus = 2
	KitchenOrderStatus_kitchenOrderStatusCooked  KitchenOrderStatus = 3
)

// Enum value maps for KitchenOrderStatus.
var (
	KitchenOrderStatus_name = map[int32]string{
		0: "KitchenOrderStatusInvalid",
		1: "kitchenOrderStatusNew",
		2: "kitchenOrderStatusCooking",
		3: "kitchenOrderStatusCooked",
	}
	KitchenOrderStatus_value = map[string]int32{
		"KitchenOrderStatusInvalid": 0,
		"kitchenOrderStatusNew":     1,
		"kitchenOrderStatusCooking": 2,
		"kitchenOrderStatusCooked":  3,
	}
)

func (x KitchenOrderStatus) Enum() *KitchenOrderStatus {
	p := new(KitchenOrderStatus)
	*p = x
	return p
}

func (x KitchenOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KitchenOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kitchen_api_proto_enumTypes[0].Descriptor()
}

func (KitchenOrderStatus) Type() protoreflect.EnumType {
	return &file_kitchen_api_proto_enumTypes[0]
}

func (x KitchenOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KitchenOrderStatus.Descriptor instead.
func (KitchenOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status KitchenOrderStatus `protobuf:"varint,2,opt,name=status,proto3,enum=kitchen_api.v1.KitchenOrderStatus" json:"status,omitempty"`
	Items  []*OrderItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetStatus() KitchenOrderStatus {
	if x != nil {
		return x.Status
	}
	return KitchenOrderStatus_KitchenOrderStatusInvalid
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetCookOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetCookOrdersRequest) Reset() {
	*x = GetCookOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCookOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookOrdersRequest) ProtoMessage() {}

func (x *GetCookOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetCookOrdersRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetCookOrdersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetCookOrdersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCookOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total  int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetCookOrdersResponse) Reset() {
	*x = GetCookOrdersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCookOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookOrdersResponse) ProtoMessage() {}

func (x *GetCookOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetCookOrdersResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetCookOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetCookOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CookingStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *CookingStartRequest) Reset() {
	*x = CookingStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookingStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookingStartRequest) ProtoMessage() {}

func (x *CookingStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookingStartRequest.ProtoReflect.Descriptor instead.
func (*CookingStartRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{4}
}

func (x *CookingStartRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CookingStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CookingStartResponse) Reset() {
	*x = CookingStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookingStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookingStartResponse) ProtoMessage() {}

func (x *CookingStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookingStartResponse.ProtoReflect.Descriptor instead.
func (*CookingStartResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{5}
}

type CookingEndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *CookingEndRequest) Reset() {
	*x = CookingEndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookingEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookingEndRequest) ProtoMessage() {}

func (x *CookingEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookingEndRequest.ProtoReflect.Descriptor instead.
func (*CookingEndRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{6}
}

func (x *CookingEndRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CookingEndResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CookingEndResponse) Reset() {
	*x = CookingEndResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookingEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookingEndResponse) ProtoMessage() {}

func (x *CookingEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookingEndResponse.ProtoReflect.Descriptor instead.
func (*CookingEndResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_api_proto_rawDescGZIP(), []int{7}
}

var File_kitchen_api_proto protoreflect.FileDescriptor

var file_kitchen_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x84, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6b, 0x69,
	0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x74,
	0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x5c, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x30, 0x0a, 0x13, 0x43, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2e, 0x0a, 0x11, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x8b, 0x01, 0x0a, 0x12, 0x4b, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x0a, 0x19, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x19, 0x0a,
	0x15, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4e, 0x65, 0x77, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x6b, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x6b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x6f,
	0x6b, 0x65, 0x64, 0x10, 0x03, 0x32, 0x84, 0x03, 0x0a, 0x07, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65,
	0x6e, 0x12, 0x70, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x24, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x86, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x23, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6b, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x12, 0x23, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x2f, 0x7b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x63,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x7e, 0x0a, 0x0a,
	0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x12, 0x21, 0x2e, 0x6b, 0x69, 0x74,
	0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x12, 0x21, 0x2f, 0x76, 0x31, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x7b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d,
	0x2f, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x65, 0x6e, 0x64, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kitchen_api_proto_rawDescOnce sync.Once
	file_kitchen_api_proto_rawDescData = file_kitchen_api_proto_rawDesc
)

func file_kitchen_api_proto_rawDescGZIP() []byte {
	file_kitchen_api_proto_rawDescOnce.Do(func() {
		file_kitchen_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_kitchen_api_proto_rawDescData)
	})
	return file_kitchen_api_proto_rawDescData
}

var file_kitchen_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kitchen_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kitchen_api_proto_goTypes = []interface{}{
	(KitchenOrderStatus)(0),       // 0: kitchen_api.v1.KitchenOrderStatus
	(*Order)(nil),                 // 1: kitchen_api.v1.Order
	(*OrderItem)(nil),             // 2: kitchen_api.v1.OrderItem
	(*GetCookOrdersRequest)(nil),  // 3: kitchen_api.v1.GetCookOrdersRequest
	(*GetCookOrdersResponse)(nil), // 4: kitchen_api.v1.GetCookOrdersResponse
	(*CookingStartRequest)(nil),   // 5: kitchen_api.v1.CookingStartRequest
	(*CookingStartResponse)(nil),  // 6: kitchen_api.v1.CookingStartResponse
	(*CookingEndRequest)(nil),     // 7: kitchen_api.v1.CookingEndRequest
	(*CookingEndResponse)(nil),    // 8: kitchen_api.v1.CookingEndResponse
}
var file_kitchen_api_proto_depIdxs = []int32{
	0, // 0: kitchen_api.v1.Order.status:type_name -> kitchen_api.v1.KitchenOrderStatus
	2, // 1: kitchen_api.v1.Order.items:type_name -> kitchen_api.v1.OrderItem
	1, // 2: kitchen_api.v1.GetCookOrdersResponse.orders:type_name -> kitchen_api.v1.Order
	3, // 3: kitchen_api.v1.Kitchen.GetCookOrders:input_type -> kitchen_api.v1.GetCookOrdersRequest
	5, // 4: kitchen_api.v1.Kitchen.CookingStart:input_type -> kitchen_api.v1.CookingStartRequest
	7, // 5: kitchen_api.v1.Kitchen.CookingEnd:input_type -> kitchen_api.v1.CookingEndRequest
	4, // 6: kitchen_api.v1.Kitchen.GetCookOrders:output_type -> kitchen_api.v1.GetCookOrdersResponse
	6, // 7: kitchen_api.v1.Kitchen.CookingStart:output_type -> kitchen_api.v1.CookingStartResponse
	8, // 8: kitchen_api.v1.Kitchen.CookingEnd:output_type -> kitchen_api.v1.CookingEndResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kitchen_api_proto_init() }
func file_kitchen_api_proto_init() {
	if File_kitchen_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kitchen_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCookOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCookOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookingStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookingStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookingEndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookingEndResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kitchen_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitchen_api_proto_goTypes,
		DependencyIndexes: file_kitchen_api_proto_depIdxs,
		EnumInfos:         file_kitchen_api_proto_enumTypes,
		MessageInfos:      file_kitchen_api_proto_msgTypes,
	}.Build()
	File_kitchen_api_proto = out.File
	file_kitchen_api_proto_rawDesc = nil
	file_kitchen_api_proto_goTypes = nil
	file_kitchen_api_proto_depIdxs = nil
}
